### ISSUE TITLE
Name of Repository is misleading

### ISSUE THREAD

**Issue by PranavMathur** [Thunderbots5604/2015-Code#1]
This repository contains code that is not for 2015, as the years are separated by package.

**Comment by danielgrimshaw** [comment]
@ZachOhara , @PranavMathur I require admin privileges to do this.

**Comment by PranavMathur** [comment]
By assigning @danielgrimshaw to this issue, I expect him to come up with a new name for the repository. After that is completed, he may tell us the new name and @Thunderbots5604/admins will change it. @danielgrimshaw does not need admin rights.

**Comment by PranavMathur** [comment]
@danielgrimshaw, any progress?

**Comment by PranavMathur** [comment]
@danielgrimshaw, any progress?

**Comment by PranavMathur** [comment]
@danielgrimshaw, any progress?

**Comment by PranavMathur** [comment]
@danielgrimshaw, any progress?

**Comment by ZachOhara** [comment]
Pls Pranav

**Comment by JakeOhara** [comment]
@danielgrimshaw, any progress?

**Comment by PranavMathur** [comment]
@danielgrimshaw, any progress?

**Comment by JakeOhara** [comment]
@danielgrimshaw, any progress?

**Comment by knightsean00** [comment]
@danielgrimshaw, any progress?

**Comment by ZachOhara** [comment]
There are no memes allowed on GitHub.

If there are further questions, rest assured that @danielgrimshaw has not made any progress.

**Comment by JakeOhara** [comment]
reopened; issue is not resolved.

**Comment by PranavMathur** [comment]
@danielgrimshaw, any progress?

**Comment by JakeOhara** [comment]
@danielgrimshaw, any progress?

**Comment by PranavMathur** [comment]
@danielgrimshaw, any progress?

**Comment by JakeOhara** [comment]
@danielgrimshaw, any progress?

**Comment by knightsean00** [comment]
Don't worry guys I'll make you proud

**Comment by JakeOhara** [comment]
Closed; we already came to the consensus that this issue would stay closed.
